server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(png|jpg|jpeg|gif|ico|css|js|ttf|woff|woff2)$ {
        expires 1d;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}